export const dummyDateRange = {
  startDate: '2026-09-01',
  endDate: '2026-09-23',
}

export const dummyDeveloperReport = {
  accountType: 'developer',
  generatedAt: '2026-09-23T11:00:00.000Z',
  identity: {
    name: 'Skyline Estates',
    slogan: 'Homes that hold their value',
    slug: 'skyline-estates',
    email: 'hello@skylineestates.gh',
    phone: '+233 24 555 0180',
    secondary_email: 'sales@skylineestates.gh',
    secondary_phone: '+233 30 266 4400',
    website: 'https://skylineestates.gh',
    address: '12 Liberation Road',
    city: 'Accra',
    region: 'Greater Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    license_number: 'RE-DEV-2041',
    founded_year: 2014,
    company_size: '50-100',
    verified: true,
    account_status: 'active',
    admin_status: 'approved',
    profile_completion_percentage: 86,
    specialization: { database: ['Residential', 'Mixed-use'], custom: ['Affordable housing'] },
    default_currency: { code: 'GHS', name: 'Ghanaian Cedi' },
    total_developments: 6,
    total_units: 142,
    company_locations: [
      { city: 'Accra', region: 'Greater Accra', country: 'Ghana', currency: 'GHS', primary_location: true },
      { city: 'Tema', region: 'Greater Accra', country: 'Ghana', currency: 'GHS', primary_location: false },
    ],
  },
  team: {
    total: 12,
    active: 10,
    pending: 2,
    byRole: [
      { role: 'Super Admin', count: 1 },
      { role: 'Admin', count: 2 },
      { role: 'Manager', count: 3 },
      { role: 'Editor', count: 4 },
      { role: 'Viewer', count: 2 },
    ],
    roster: [
      { first_name: 'Ama', last_name: 'Boateng', role: 'Super Admin', status: 'active', last_active: '2026-09-23' },
      { first_name: 'Kojo', last_name: 'Mensah', role: 'Manager', status: 'active', last_active: '2026-09-22' },
      { first_name: 'Efua', last_name: 'Nyarko', role: 'Editor', status: 'active', last_active: '2026-09-22' },
      { first_name: 'Yaw', last_name: 'Owusu', role: 'Viewer', status: 'pending', last_active: null },
      { first_name: 'Linda', last_name: 'Sarpong', role: 'Admin', status: 'active', last_active: '2026-09-21' },
    ],
  },
  analytics: {
    profile_views: 184,
    unique_profile_viewers: 129,
    profile_views_from_home: 42,
    profile_views_from_listings: 91,
    profile_views_from_search: 51,
    total_listings: 24,
    active_listings: 18,
    sold_listings: 4,
    rented_listings: 2,
    total_listing_views: 2460,
    total_listing_leads: 87,
    total_listing_sales: 6,
    total_impressions_received: 1184,
    impression_social_media_received: 310,
    impression_website_visit_received: 226,
    impression_share_received: 498,
    impression_saved_listing_received: 150,
    total_views: 2644,
    total_leads: 91,
    unique_leads: 58,
    anonymous_leads: 33,
    leads_initiated: 91,
    appointments_booked: 14,
    overall_conversion_rate: 3.5,
    view_to_lead_rate: 3.5,
    lead_to_sale_rate: 6.6,
    profile_to_lead_rate: 4.9,
    profile_views_change: { change: 22, current: 184, previous: 162, change_percentage: 13.6 },
    impressions_change: { change: 140, current: 1184, previous: 1044, change_percentage: 13.4 },
    leads_change: { change: 11, current: 91, previous: 80, change_percentage: 13.8 },
    views_change: { change: 310, current: 2644, previous: 2334, change_percentage: 13.3 },
    conversion_change: { change: 0.4, current: 3.5, previous: 3.1, change_percentage: 12.9 },
    lead_source_breakdown: {
      iskahomes: { amount: 38, percentage: 41.8, context_breakdown: { search: { amount: 18, percentage: 47.4 }, home: { amount: 12, percentage: 31.6 }, profile: { amount: 8, percentage: 21.0 } } },
      whatsapp: { amount: 22, percentage: 24.2 },
      copy_link: { amount: 14, percentage: 15.4 },
      referral: { amount: 9, percentage: 9.9 },
      facebook: { amount: 8, percentage: 8.7 },
    },
  },
  listings: {
    listing_status: { draft: 3, active: 18, archived: 1, sold: 4, rented: 2 },
    visibility: { public: 16, hidden: 8 },
    admin_status: { approved: 20, pending: 2, blocked: 0 },
    price_type: { sale: 15, rent: 7, lease: 2 },
    highlights: {
      bestByViews: {
        title: '3-Bed Terrace — East Legon Hills',
        city: 'Accra',
        listing_status: 'active',
        total_views: 612,
        total_leads: 19,
      },
      bestByLeads: {
        title: '2-Bed Apartment — Cantonments',
        city: 'Accra',
        listing_status: 'active',
        total_views: 408,
        total_leads: 24,
      },
      bestConversion: {
        title: 'Studio Loft — Airport Residential',
        city: 'Accra',
        listing_status: 'active',
        total_views: 190,
        total_leads: 14,
      },
      bestDevelopment: {
        title: 'Harbour Ridge',
        city: 'Tema',
        status: 'Under Construction',
        total_units: 36,
        units_sold: 4,
        total_views: 980,
        total_leads: 31,
      },
    },
    topListings: [
      { title: '3-Bed Terrace — East Legon Hills', listing_type: 'unit', city: 'Accra', listing_status: 'active', status: 'Available', visibility: true, admin_status: 'approved', price_type: 'sale', total_views: 612, total_leads: 19 },
      { title: '2-Bed Apartment — Cantonments', listing_type: 'unit', city: 'Accra', listing_status: 'active', status: 'Available', visibility: true, admin_status: 'approved', price_type: 'rent', total_views: 408, total_leads: 24 },
      { title: 'Family Villa — Trasacco', listing_type: 'unit', city: 'Accra', listing_status: 'sold', status: 'Sold', visibility: true, admin_status: 'approved', price_type: 'sale', total_views: 355, total_leads: 11 },
      { title: 'Studio Loft — Airport Residential', listing_type: 'unit', city: 'Accra', listing_status: 'active', status: 'Available', visibility: true, admin_status: 'approved', price_type: 'rent', total_views: 190, total_leads: 14 },
      { title: '4-Bed Duplex — Spintex', listing_type: 'unit', city: 'Accra', listing_status: 'active', status: 'Available', visibility: false, admin_status: 'pending', price_type: 'sale', total_views: 176, total_leads: 8 },
    ],
    topDevelopments: [
      { title: 'Harbour Ridge', status: 'Under Construction', development_status: 'active', total_units: 36, units_sold: 4, total_views: 980, total_leads: 31, total_revenue: 2870000 },
      { title: 'Oak Court Residences', status: 'Ready for Occupancy', development_status: 'active', total_units: 22, units_sold: 2, total_views: 640, total_leads: 18, total_revenue: 1100000 },
      { title: 'Westbrook Gardens', status: 'Planning', development_status: 'draft', total_units: 48, units_sold: 0, total_views: 210, total_leads: 6, total_revenue: 0 },
    ],
  },
  leads: {
    lead_type: { automated: 81, manual: 10 },
    lead_classification: { Premium: 8, 'High Value': 21, Standard: 62 },
    pipeline: { new: 27, contacted: 18, scheduled: 12, responded: 11, closed: 14, cold_lead: 5, abandoned: 4 },
    action_mix: { lead_phone: 29, lead_message: 38, lead_appointment: 14, lead_manual: 10 },
    bestHour: { hour: 11, label: '11 AM', leads: 18, conversions: 3, conversion_rate: 16.7 },
    bestDay: { day: 'Tuesday', leads: 22, conversions: 4, conversion_rate: 18.2 },
    bestWeek: { week: '2026-W37', label: '8–14 Sep', leads: 31, conversions: 5, conversion_rate: 16.1 },
    hourOfDay: [
      { hour: 8, total: 6 },
      { hour: 9, total: 11 },
      { hour: 10, total: 14 },
      { hour: 11, total: 18 },
      { hour: 12, total: 9 },
      { hour: 13, total: 7 },
      { hour: 14, total: 10 },
      { hour: 15, total: 8 },
      { hour: 16, total: 5 },
    ],
    topContexts: [
      { name: 'search', amount: 31 },
      { name: 'home', amount: 24 },
      { name: 'profile', amount: 18 },
    ],
  },
  chargeables: {
    types: [
      { name: 'Service charge', default_amount: 450, default_interval_value: 1, default_interval_unit: 'month', attached_listings: 18, collected_revenue: 32400, outstanding_revenue: 8100, overdue_revenue: 450 },
      { name: 'Ground rent', default_amount: 1200, default_interval_value: 1, default_interval_unit: 'year', attached_listings: 12, collected_revenue: 14400, outstanding_revenue: 12000, overdue_revenue: 1200 },
      { name: 'Parking', default_amount: 150, default_interval_value: 1, default_interval_unit: 'month', attached_listings: 9, collected_revenue: 4800, outstanding_revenue: 2700, overdue_revenue: 150 },
    ],
    entries: [
      { chargeable_type: 'Service charge', unit_title: 'Harbour Ridge B12', client_name: 'Akua Mensah', client_email: 'akua.mensah@gmail.com', client_phone: '+233 24 811 2201', amount: 450, interval_value: 1, interval_unit: 'month', period_start: '2026-09-01', period_end: '2026-09-30', status: 'Paid', next_due_status: 'paid', overdue_time: 0, paid_at: '2026-09-04', billing_reference: 'SC-2041' },
      { chargeable_type: 'Service charge', unit_title: 'Oak Court 8', client_name: 'Daniel Owusu', client_email: 'daniel.owusu@outlook.com', client_phone: '+233 20 445 1188', amount: 450, interval_value: 1, interval_unit: 'month', period_start: '2026-09-01', period_end: '2026-09-30', status: 'Pending', next_due_status: 'due', overdue_time: 0, paid_at: null, billing_reference: 'SC-2048' },
      { chargeable_type: 'Ground rent', unit_title: 'East Legon Hills T3', client_name: 'Nana Yaa Boateng', client_email: 'nanayaa@skymail.gh', client_phone: '+233 54 902 3310', amount: 1200, interval_value: 1, interval_unit: 'year', period_start: '2026-01-01', period_end: '2026-12-31', status: 'Pending', next_due_status: 'overdue', overdue_time: 34, paid_at: null, billing_reference: 'GR-118' },
      { chargeable_type: 'Service charge', unit_title: 'Westbrook Gardens A4', client_name: 'Seth Quaye', client_email: 'seth.quaye@gmail.com', client_phone: '+233 27 661 0944', amount: 450, interval_value: 1, interval_unit: 'month', period_start: '2026-08-01', period_end: '2026-08-31', status: 'Pending', next_due_status: 'overdue', overdue_time: 19, paid_at: null, billing_reference: 'SC-1992' },
      { chargeable_type: 'Parking', unit_title: 'Cantonments 2B', client_name: null, client_email: null, client_phone: null, amount: 150, interval_value: 1, interval_unit: 'month', period_start: '2026-07-01', period_end: '2026-07-31', status: 'Pending', next_due_status: 'overdue', overdue_time: 12, paid_at: null, billing_reference: 'PK-77' },
      { chargeable_type: 'Parking', unit_title: 'Airport Residential Studio', client_name: 'Ivy Boateng', client_email: 'ivy.b@icloud.com', client_phone: null, amount: 150, interval_value: 1, interval_unit: 'month', period_start: '2026-09-01', period_end: '2026-09-30', status: 'Paid', next_due_status: 'paid', overdue_time: 0, paid_at: '2026-09-08', billing_reference: 'PK-81' },
    ],
    totals: {
      paid_amount: 51600,
      still_due_amount: 22800,
      overdue_amount: 1800,
      paid_count: 11,
      still_due_count: 7,
      overdue_count: 3,
      due_count: 4,
      average_overdue_days: 21.7,
      longest_overdue_days: 34,
    },
  },
  sales: {
    totalRevenue: 4180000,
    expectedRevenue: 12650000,
    totalUnitsSold: 4,
    totalUnitsRented: 2,
    averageSalesTime: 41,
    leadsToSales: 6.6,
    averageSalePrice: 1045000,
    by_purpose: [
      { name: 'Sale', count: 4, revenue: 4180000 },
      { name: 'Rent', count: 2, revenue: 8300 },
    ],
    by_type: [
      { name: 'House', count: 3, revenue: 3260000 },
      { name: 'Apartment', count: 2, revenue: 924500 },
      { name: 'Land', count: 1, revenue: 0 },
    ],
    by_subtype: [
      { name: 'Detached', count: 1, revenue: 1850000 },
      { name: 'Terrace', count: 1, revenue: 920000 },
      { name: 'Duplex', count: 1, revenue: 310000 },
      { name: 'Studio', count: 1, revenue: 4500 },
      { name: '2 Bedroom', count: 2, revenue: 1103800 },
    ],
    by_country: [
      { name: 'Ghana', count: 6, revenue: 4188300 },
    ],
    by_region: [
      { name: 'Greater Accra', count: 5, revenue: 3878300 },
      { name: 'Ashanti', count: 1, revenue: 310000 },
    ],
    records: [
      { title: 'Family Villa — Trasacco', sale_type: 'sold', sale_price: 1850000, asv: 1780000, currency: 'GHS', sale_date: '2026-09-18', buyer_name: 'Kofi Adjei', sale_source: 'Iska Homes', purpose: 'Sale', type: 'House', subtype: 'Detached', country: 'Ghana', region: 'Greater Accra', commission_amount: null },
      { title: 'Harbour Ridge B12', sale_type: 'sold', sale_price: 920000, asv: 920000, currency: 'GHS', sale_date: '2026-09-12', buyer_name: 'Akua Mensah', sale_source: 'Iska Homes', purpose: 'Sale', type: 'Apartment', subtype: '2 Bedroom', country: 'Ghana', region: 'Greater Accra', commission_amount: null },
      { title: 'Airport Residential Studio', sale_type: 'rented', sale_price: 4500, asv: 4500, currency: 'GHS', sale_date: '2026-09-09', buyer_name: 'Ivy Boateng', sale_source: 'Iska Homes', purpose: 'Rent', type: 'Apartment', subtype: 'Studio', country: 'Ghana', region: 'Greater Accra', commission_amount: null },
      { title: 'Oak Court 8', sale_type: 'sold', sale_price: 1100000, asv: 1040000, currency: 'GHS', sale_date: '2026-09-04', buyer_name: 'Daniel Owusu', sale_source: 'Iska Homes', purpose: 'Sale', type: 'House', subtype: '2 Bedroom', country: 'Ghana', region: 'Greater Accra', commission_amount: null },
      { title: 'Cantonments 2B', sale_type: 'rented', sale_price: 3800, asv: 3800, currency: 'GHS', sale_date: '2026-09-02', buyer_name: 'Kwesi Addo', sale_source: 'Walk-in', purpose: 'Rent', type: 'Apartment', subtype: '2 Bedroom', country: 'Ghana', region: 'Greater Accra', commission_amount: null },
      { title: 'Spintex Duplex 4', sale_type: 'sold', sale_price: 310000, asv: 295000, currency: 'GHS', sale_date: '2026-09-01', buyer_name: 'Abena Sarpong', sale_source: 'Iska Homes', purpose: 'Sale', type: 'House', subtype: 'Duplex', country: 'Ghana', region: 'Ashanti', commission_amount: null },
    ],
  },
}

export const dummyAgencyReport = {
  ...dummyDeveloperReport,
  accountType: 'agency',
  identity: {
    ...dummyDeveloperReport.identity,
    name: 'Northline Agency',
    slogan: 'Local knowledge, national reach',
    slug: 'northline-agency',
    email: 'desk@northline.gh',
    license_number: 'RE-AG-1182',
    specialization: { database: [], custom: [] },
    total_developments: 0,
    total_units: 0,
    total_agents: 9,
    active_agents: 8,
    commission_rate: { default: 3.0 },
  },
  team: {
    ...dummyDeveloperReport.team,
    total: 4,
    active: 3,
    pending: 1,
    agents: { total_agents: 9, active_agents: 8 },
    byRole: [
      { role: 'Super Admin', count: 1 },
      { role: 'Admin', count: 1 },
      { role: 'Manager', count: 1 },
      { role: 'Viewer', count: 1 },
    ],
    roster: [
      { first_name: 'Naa', last_name: 'Adjei', role: 'Super Admin', status: 'active', last_active: '2026-09-23' },
      { first_name: 'Prince', last_name: 'Tetteh', role: 'Manager', status: 'active', last_active: '2026-09-22' },
      { first_name: 'Akosua', last_name: 'Dede', role: 'Admin', status: 'active', last_active: '2026-09-20' },
      { first_name: 'Isaac', last_name: 'Quaye', role: 'Viewer', status: 'pending', last_active: null },
    ],
  },
  listings: {
    ...dummyDeveloperReport.listings,
    highlights: {
      ...dummyDeveloperReport.listings.highlights,
      bestDevelopment: null,
      bestAgent: {
        name: 'Kwesi Addo',
        total_listings: 11,
        total_views: 740,
        total_leads: 28,
      },
    },
    topDevelopments: [],
    topListings: dummyDeveloperReport.listings.topListings.map((row) => ({
      ...row,
      listing_type: 'property',
    })),
  },
  sales: {
    ...dummyDeveloperReport.sales,
    commission_paid: 18600,
    commission_pending: 12400,
    records: dummyDeveloperReport.sales.records.map((row, index) => ({
      ...row,
      commission_amount: index % 2 === 0 ? 18600 / 2 : null,
      commission_rate: 3,
    })),
  },
  agents: {
    total_agents: 9,
    active_agents: 8,
    inactive_agents: 1,
    roster: [
      { name: 'Kwesi Addo', email: 'kwesi.addo@northline.gh', phone: '+233 24 701 1182', agent_status: 'active', total_listings: 11, active_listings: 8, total_views: 740, total_leads: 28, total_sales: 2, total_revenue: 1853800, commission_amount: 9300 },
      { name: 'Ama Serwaa', email: 'ama.serwaa@northline.gh', phone: '+233 20 554 0911', agent_status: 'active', total_listings: 7, active_listings: 6, total_views: 412, total_leads: 15, total_sales: 1, total_revenue: 1100000, commission_amount: 3300 },
      { name: 'Joseph Mensah', email: 'joseph.mensah@northline.gh', phone: '+233 27 443 2208', agent_status: 'active', total_listings: 5, active_listings: 4, total_views: 288, total_leads: 11, total_sales: 1, total_revenue: 920000, commission_amount: 2760 },
      { name: 'Efua Darko', email: 'efua.darko@northline.gh', phone: '+233 55 882 1044', agent_status: 'active', total_listings: 4, active_listings: 3, total_views: 196, total_leads: 8, total_sales: 1, total_revenue: 310000, commission_amount: 930 },
      { name: 'Ibrahim Sule', email: 'ibrahim.sule@northline.gh', phone: '+233 24 990 3317', agent_status: 'inactive', total_listings: 2, active_listings: 0, total_views: 41, total_leads: 1, total_sales: 0, total_revenue: 0, commission_amount: 0 },
    ],
  },
}

export function getDummyReport(accountType = 'developer') {
  return accountType === 'agency' ? dummyAgencyReport : dummyDeveloperReport
}
